### ISSUE TITLE
Add device again, error occurred

### ISSUE THREAD

**Issue by suicun93** [SonyCSL/OpenECHO#9]
Steps:
Device device = new Device();
1. Node.addDevice(device); // success
2. Node.Remove(device); // success
3. Node.addDevice(device); // Failed

https://github.com/SonyCSL/OpenECHO/blob/724895204ad672658f3de9d7c19a3df99e883ef2/src/com/sonycsl/echo/node/EchoNode.java#L126

	`public void removeDevice(DeviceObject device) {
		if(device == null) return;
		if(device.getNode() != this) return;
		mDevices.remove(device);
	}`

I found that when remove Device, you forgot to remove Device's father node.
Please Fix this.
It is so easy.

**Comment by sowd** [comment]
Thank you @tokuhisa !
Did it solve the problem, @suicun93 ?

**Comment by suicun93** [comment]
そのバグは修正されました
ありがとうございます
